title: OmenMon
description: Omen Hardware Monitoring & Control
show_title: true
show_description: true
show_header_link1: true
show_header_link2: true
show_header_link3: true
show_downloads: false
google_analytics: false
remote_theme: OmenMon/Theme

omenmon:
  header_link1_text: Button 1
  header_link1_url: https://1/
  header_link2_text: Button 2
  header_link2_url: https://2/
  header_link3_text: Button 3
  header_link3_url: https://3/
  footer_link_text: OmenMon
  footer_link_text_after: After
  footer_link_text_before: Before
  footer_link_url: https://github.com/OmenMon/
  footer_disclaimer: © 2023
