# OmenMon Web Page
# Configuration

remote_theme: OmenMon/Theme

title: OmenMon
description: Omen Hardware Monitoring & Control

defaults:
  -
    scope:
      path: "" # Any File
      type: "pages"
    values:
      layout: "default"
      suppress_header: false
      suppress_logo: false
      suppress_title: false
      suppress_description: false
      suppress_menu: false
      menu:
        -
          link: /
          text: About
        -
          link: /features/
          text: Features
        -
          link: /gui/
          text: Graphical Interface
        -
          link: /cli/
          text: Command Line
        -
          link: /config/
          text: Configuration
        -
          link: /build/
          text: Building
        -
          link: /more/
          text: Other Info
        -
          id: dl
          link: https://github.com/OmenMon/OmenMon/releases/latest
          text: Download
      footer-link:
        -
          link: https://github.com/OmenMon/
          text: OmenMon
      footer-disclaimer: © 2023
